controller_manager:
  ros__parameters:
    update_rate: 100

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.160
    wheel_radius: 0.033
    use_stamped_vel: false
    base_frame_id: base_footprint
    publish_rate: 50.0
    open_loop: true
    velocity_rolling_window_size: 10

    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
